name: Run all tests

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

env:
  PYTHONIOENCODING: UTF-8

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
            venv-path: source venv/bin/activate
          - os: macos-latest
            path: ~/Library/Caches/pip
            venv-path: source venv/bin/activate
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
            venv-path: venv\Scripts\activate.bat
        python-version: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Run tests
        run: |
          python -m unittest tests.test_bank_methods.AlfaStatusLeadTestCase
          python -m unittest tests.test_bank_methods.AlfaScoringTestCaset
          python -m unittest tests.test_bank_methods.AlfaLeadTestCase
          python -m unittest tests.test_bank_methods.VTBStatusLeadTestCase
          python -m unittest tests.test_bank_methods.VTBScoringTestCase
          python -m unittest tests.test_bank_methods.VTBLeadTestCase
#          python -m unittest tests.test_bank_methods.TochkaStatusLeadTestCase
#          python -m unittest tests.test_bank_methods.TochkaLeadTestCase
#          python -m unittest tests.test_bank_methods.TochkaRegistryUrTestCase
#          python -m unittest tests.test_bank_methods.ModuleLeadTestCase
#          python -m unittest tests.test_bank_methods.MoeDeloLeadTestCase
#          python -m unittest tests.test_bank_methods.OpenStatusLeadTestCase
#          python -m unittest tests.test_bank_methods.OpenScoringTestCase
#          python -m unittest tests.test_bank_methods.OpenScoringIDTestCase
#          python -m unittest tests.test_bank_methods.OpenScoringStatusTestCase
#          python -m unittest tests.test_bank_methods.OpenLeadTestCase
